## Pytorch学习1

In [2]:
import torch

In [4]:
x = torch.empty(4,3)
print x

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [5]:
x = torch.rand(5,3)
print x

tensor([[0.5769, 0.5001, 0.2135],
        [0.5919, 0.8209, 0.9657],
        [0.4994, 0.9044, 0.6700],
        [0.5123, 0.8308, 0.9390],
        [0.8255, 0.3361, 0.1005]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print x

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print x

x = torch.randn_like(x, dtype=torch.float)
print x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0462,  0.0597, -0.0527],
        [ 2.3843,  0.7157,  0.6547],
        [-1.3518,  1.1711,  1.0058],
        [-1.2887,  0.6930,  0.1356],
        [ 1.2648, -1.1355,  0.2385]])


In [11]:
print x.size()

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)
print x+y

tensor([[ 1.3582,  0.1314,  0.7306],
        [ 2.8311,  1.0747,  1.1183],
        [-0.4428,  1.7434,  1.1951],
        [-1.1680,  1.2326,  0.2013],
        [ 1.3873, -0.6474,  1.1269]])


In [13]:
print torch.add(x, y)

tensor([[ 1.3582,  0.1314,  0.7306],
        [ 2.8311,  1.0747,  1.1183],
        [-0.4428,  1.7434,  1.1951],
        [-1.1680,  1.2326,  0.2013],
        [ 1.3873, -0.6474,  1.1269]])


In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print result

tensor([[ 1.3582,  0.1314,  0.7306],
        [ 2.8311,  1.0747,  1.1183],
        [-0.4428,  1.7434,  1.1951],
        [-1.1680,  1.2326,  0.2013],
        [ 1.3873, -0.6474,  1.1269]])


In [15]:
print x

print y

tensor([[ 1.0462,  0.0597, -0.0527],
        [ 2.3843,  0.7157,  0.6547],
        [-1.3518,  1.1711,  1.0058],
        [-1.2887,  0.6930,  0.1356],
        [ 1.2648, -1.1355,  0.2385]])
tensor([[0.3119, 0.0716, 0.7833],
        [0.4468, 0.3590, 0.4636],
        [0.9090, 0.5723, 0.1893],
        [0.1207, 0.5395, 0.0657],
        [0.1224, 0.4881, 0.8884]])


In [16]:
y.add_(x)
print y

tensor([[ 1.3582,  0.1314,  0.7306],
        [ 2.8311,  1.0747,  1.1183],
        [-0.4428,  1.7434,  1.1951],
        [-1.1680,  1.2326,  0.2013],
        [ 1.3873, -0.6474,  1.1269]])


In [17]:
print x[:, 1]

tensor([ 0.0597,  0.7157,  1.1711,  0.6930, -1.1355])


In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print x.size(), y.size(), z.size()

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
x = torch.randn(1)
print x
print x.item() + 1

tensor([1.3782])
2.37823796272


In [23]:
a = torch.ones(5)
print a

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print b

[1. 1. 1. 1. 1.]


In [53]:
a.add_(1)
print a
print b

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print a
print b

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
if torch.cuda.is_available():
    y = torch.ones_like(x, device="cuda")
    x = x.to("cuda")
    z = x + y
    print z
    print z.to("cpu", torch.double)

tensor([2.3782], device='cuda:0')
tensor([2.3782], dtype=torch.float64)


In [27]:
i = torch.LongTensor([[0, 1, 1],
                      [2, 0, 2]])
v = torch.FloatTensor([3, 4, 5])
a = torch.sparse_coo_tensor(i, v, torch.Size([2, 4]), device="cuda")
print a.to("cpu")

torch.sparse.FloatTensor of size (2,4) with indices:
tensor([[0, 1, 1],
        [2, 0, 2]])
and values:
tensor([3., 4., 5.])


In [28]:
a = torch.arange(5)
b = torch.arange(1, 4)
c = torch.arange(1, 2.5, 0.5)
print a; b; c

tensor([0, 1, 2, 3, 4])


tensor([1.0000, 1.5000, 2.0000])

In [91]:
x = torch.randn(2, 3)
a = torch.cat((x, x, x), 0)
print torch.chunk(a, 3)

(tensor([[-1.2008,  0.2366, -0.6626],
        [-1.3040,  1.7334,  0.1933]]), tensor([[-1.2008,  0.2366, -0.6626],
        [-1.3040,  1.7334,  0.1933]]), tensor([[-1.2008,  0.2366, -0.6626],
        [-1.3040,  1.7334,  0.1933]]))
